version: '3.0'

services:
  grafana:
    container_name: 'iotopen-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.8}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/iotopen-datasource
      - ./provisioning:/etc/grafana/provisioning
